version: '3.3'
services:
  mongo:
    image: mongodb_ordar_img
    build: ./Docker/MongoDB
    container_name: mongodb_ordar
    env_file:
     - Configure.env
    command: ./initmongo.sh
    volumes:
     - mongodb:/data/db
    ports: 
     - "127.0.0.1:27018:27017"
    restart: unless-stopped
  

  mysql_db:
    image: mysql_ordar_img
    build: ./Docker/MYSQL
    container_name: mysql_ordar
    env_file:
     - Configure.env
    volumes:
     - mysql:/var/lib/mysql

  
  elasticsearch:
    image: elasticsearch_ordar_img
    build: ./Docker/ElasticSearch
    container_name: elasticsearch_ordar
    environment: 
     - cluster.name=Ordar
     - xpack.security.enabled=false
     - number_of_replicas=0
    volumes:
     - elasticsearch:/usr/share/elasticsearch/data


  mongo-connector:
    image: mongo-connector_ordar_img
    build: ./Docker/MongoConnector
    container_name: mongo-connector_ordar
    env_file:
     - Configure.env
    depends_on:
     - OrdarUI
     - elasticsearch
     - mongo
    links:
     - elasticsearch
     - mongo
    restart: always


  OrdarUI:
    image: ordar_ui_img
    build: .
    container_name: ordar_ui
    env_file:
     - Configure.env
    depends_on:
     - mysql_db
     - elasticsearch
     - mongo
    links:
     - mysql_db
     - elasticsearch
     - mongo
    ports: 
     - "8084:80"
    volumes:
     - /testdata/:/data/applis/ORDaR/Uploads/



  OrdarOAIPMH:
    image: ordar_oaipmh_img
    build: ./Docker/OAI-PMH
    container_name: ordar_oaipmh
    env_file:
     - Configure.env
    depends_on:
     - elasticsearch
    links:
     - elasticsearch
    ports: 
     - "127.0.0.1:8087:80"
 

  CheckEmbargoedDate:
    image: checkembargoeddate_img
    build: ./Docker/CheckEmbargoedDate
    container_name: checkembargoeddate
    env_file:
     - Configure.env
    depends_on:
     - mongo
    links:
     - mongo



# Ordar_script_mobised:
#    image: ordar_script-mobised_img
#    build: ./Docker/Ordar_script-mobised
#    container_name: ordar_script-mobised
#    env_file:
#     - Configure.env
#    depends_on:
#     - mongo
#    links:
#     - mongo
#    volumes:
#     - /testdata/:/data/applis/ORDaR/Uploads/
#     - /testdata/excel/:/data/applis/ORDaR/excel/




volumes:
  mongodb: {}
  elasticsearch : {}
  mysql: {} 
 
